# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Load secret
      uses: 1password/load-secrets-action@v1
      with:
        export-env: true
      env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: op://my1password/PyPI/token

    # - name: Print masked secret
    #   run: echo "Secret: $SECRET"

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install --upgrade setuptools wheel twine
      
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: $SECRET  # 添加你在 GitHub 仓库 Secrets 中设置的名为 PYPI_TOKEN 的 token
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*